### ISSUE TITLE
Support the SvgTeX support proposal for Pandoc!

### ISSUE THREAD

**Issue by serge-stroobandt** [agrbin/svgtex#11]
I wrote a [proposal](https://groups.google.com/forum/#!topic/pandoc-discuss/TbOlj9qv94Y) to extend [Pandoc](http://johnmacfarlane.net/pandoc/README.html#math-rendering-in-html)'s (X)HTML writer with support for SvgTex. This would allow to inject SVG math directly into the (X)HTML rendered by Pandoc.

**Please, express your support in favour of this proposal over at [the pandoc forum!](https://groups.google.com/forum/#!topic/pandoc-discuss/TbOlj9qv94Y)**

**Comment by agrbin** [comment]
Hi Serge,

I wrote a line to that forum, I hope it will be helpful for you.

Anton

**Comment by serge-stroobandt** [comment]
I saw that. Thank you very much for everything!

**Comment by serge-stroobandt** [comment]
I wrote a Haksell Pandoc JSON filter for SvgTex myself. The code is up at
https://groups.google.com/forum/#!msg/pandoc-discuss/MJggAXUmOII/
